apiVersion: apps/v1
kind: Deployment
metadata:
  name: design99-otel-collector
  namespace: design99-infrastructure
  labels:
    app: design99-otel-collector
    component: telemetry
    project: design99
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design99-otel-collector
  template:
    metadata:
      labels:
        app: design99-otel-collector
        component: telemetry
        project: design99
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.132.0
        ports:
        - containerPort: 4317
          name: grpc
        - containerPort: 4318
          name: http
        - containerPort: 8888
          name: metrics
        - containerPort: 8081
          name: health
        - containerPort: 8889
          name: prometheus
        args: ["--config=/etc/otel-collector-config.yaml"]
        volumeMounts:
        - name: otel-config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 60
          timeoutSeconds: 20
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 8
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "250m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
      volumes:
      - name: otel-config
        configMap:
          name: design99-otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: design99-otel-collector
  namespace: design99-infrastructure
  labels:
    app: design99-otel-collector
    component: telemetry
    project: design99
    port-forward: "enabled"
  annotations:
    port-forward.design99.io/ports: "4317,4318"
    port-forward.design99.io/description: "OpenTelemetry collector gRPC and HTTP"
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: metrics
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: prometheus
    port: 8889
    targetPort: 8889
    protocol: TCP
  selector:
    app: design99-otel-collector
