apiVersion: apps/v1
kind: Deployment
metadata:
  name: design99-rabbitmq
  namespace: design99-infrastructure
  labels:
    app: design99-rabbitmq
    component: message-broker
    project: design99
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design99-rabbitmq
  template:
    metadata:
      labels:
        app: design99-rabbitmq
        component: message-broker
        project: design99
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:4.1.2-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/conf.d/20-custom.conf
          subPath: rabbitmq.conf
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 180
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 15
          failureThreshold: 8
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: design99-rabbitmq-data-pvc
      - name: rabbitmq-config
        configMap:
          name: design99-rabbitmq-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: design99-rabbitmq-config
  namespace: design99-infrastructure
  labels:
    app: design99-rabbitmq
    component: message-broker
    project: design99
data:
  rabbitmq.conf: |
    # Memory and disk thresholds
    vm_memory_high_watermark.relative = 0.6
    disk_free_limit.relative = 2.0

    # Connection and channel limits
    channel_max = 2047
    connection_max = 1000

    # Heartbeat settings
    heartbeat = 60

    # Clustering and networking
    cluster_formation.peer_discovery_backend = classic_config

    # Management plugin
    management.tcp.port = 15672
    management.tcp.ip = 0.0.0.0

    # Logging
    log.console = true
    log.console.level = info

    # Performance tuning
    collect_statistics_interval = 10000

---
apiVersion: v1
kind: Service
metadata:
  name: design99-rabbitmq
  namespace: design99-infrastructure
  labels:
    app: design99-rabbitmq
    component: message-broker
    project: design99
    port-forward: "enabled"
  annotations:
    port-forward.design99.io/ports: "5672,15672"
    port-forward.design99.io/description: "RabbitMQ AMQP and Management"
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: management
    port: 15672
    targetPort: 15672
    protocol: TCP
  selector:
    app: design99-rabbitmq
